name: "Security Vulnerability Report"
description: "Report a security vulnerability or bug in the project. Please do not post public details until a fix is released."
title: "[SECURITY] "
labels: ["security", "vulnerability"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        **Thank you for helping us keep this project secure!**

        Please fill out the template below. Do **not** post this publicly until the maintainers respond.

  - type: input
    id: steps-to-reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "Provide detailed steps to reproduce the vulnerability."
      placeholder: "Step 1: ...\nStep 2: ..."

  - type: input
    id: impact
    attributes:
      label: "Potential Impact"
      description: "Describe the potential security impact of this vulnerability."
      placeholder: "E.g., unauthorized data access, code execution, etc."

  - type: textarea
    id: suggested-fix
    attributes:
      label: "Suggested Fix / Workaround"
      description: "If you have a suggestion or workaround, describe it here."
      placeholder: "Optional: explain how this could be fixed or mitigated."

  - type: markdown
    attributes:
      value: |
        **Important Links:**
        - GitHub Security Policy: [https://docs.github.com/en/code-security/security-advisories](https://docs.github.com/en/code-security/security-advisories)
        - Repository Security Page: [https://github.com/YOUR_USERNAME/YOUR_REPO/security](https://github.com/YOUR_USERNAME/YOUR_REPO/security)

  - type: dropdown
    id: severity
    attributes:
      label: "Severity Level"
      description: "Select the severity of the issue."
      options:
        - Low
        - Medium
        - High
        - Critical
