name: Build Docker Images and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'new-build')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set DATE variable
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Build all Docker Images with Compose
        run: |
          docker compose build

      - name: Save Docker Images to tar
        run: |
          docker save -o chat_${DATE}.tar project_chat
          docker save -o websearch_${DATE}.tar project_websearch
          docker save -o codeinterpreter_${DATE}.tar project_codeinterpreter
          docker save -o deepsearch_${DATE}.tar project_deepsearch

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: "docker-build-${{ env.DATE }}"
          name: "Docker Build ${{ env.DATE }}"
          files: |
            chat_${{ env.DATE }}.tar
            websearch_${{ env.DATE }}.tar
            codeinterpreter_${{ env.DATE }}.tar
            deepsearch_${{ env.DATE }}.tar
            installer.sh
            installer.bat
            
