name: Build Docker Images and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'new-build')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set DATE variable
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Build all Docker Images with Compose
        run: |
          docker compose build

      - name: Save Docker Images to tar
        run: |
          docker save -o chat.tar tontooai-chat
          docker save -o websearch.tar tontooai-websearch
          docker save -o codeinterpreter.tar tontooai-codeinterpreter
          docker save -o deepsearch.tar tontooai-deepsearch

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: "docker-build-${{ env.DATE }}"
          name: "Docker Build ${{ env.DATE }}"
          artifacts: |
            chat.tar
            websearch.tar
            codeinterpreter.tar
            deepsearch.tar
